### ISSUE TITLE
Error: "Conflicting namespace base" with Dict typing

### ISSUE THREAD

**Issue by alealv** [omni-us/jsonargparse#102]
Hi, I'm having trouble initializing 3 different functions inside a dictionary.

I have the following code:
```python
class MyDataModule(pl.LightningDataModule):
    def __init__(
        self,
        batch_size: Union[int, Dict[str, int]],
        collate_fn: Dict[str, Union[Callable, BaseCollate]],
        ....
    ):
   .........

class AudioMelCollate(BaseCollate):
    def __init__(
        self,
        mel_spec: MelSpectrogramDRC,
        max_num_frames: Optional[int] = None,
    ) -> None:
        self.max_num_frames = max_num_frames
    def __call__(self, batch):
        ....
```

And the following config files
```yaml
data:
  batch_size:
    train: 30
    dev: 10
    test: 1
  collate_fn:
    train:
      class_path: dataset.collate.AudioMelCollate
      init_args:
        max_num_frames: 32
    dev: 
      class_path: dataset.collate.AudioMelCollate
      init_args:
        max_num_frames: 100
    test:
      class_path: dataset.collate.AudioMelCollate
      init_args:
        max_num_frames: null
...
```

The config works for `batch_size`, but not for `collate_fn`. I would expect it to create an  `AudoMelCollate` class for each key ("train", "dev", "test") but it's actually falling with the following error message:

```bash
➜ env CUDA_VISIBLE_DEVICES="9" $(poetry env info -p)/bin/python vocoder/train.py fit --config configs/hifi-gan_config.yml
Traceback (most recent call last):
  File "vocoder/train.py", line 107, in <module>
    cli = AcousticModelCLI(
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.8/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 489, in __init__
    self.parse_arguments(self.parser)
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.8/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 628, in parse_arguments
    self.config = parser.parse_args()
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.8/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 233, in parse_args
    return super().parse_args(*args, **kwargs)
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.8/lib/python3.8/site-packages/jsonargparse/core.py", line 389, in parse_args
    parsed_cfg = self._parse_common(
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.8/lib/python3.8/site-packages/jsonargparse/core.py", line 315, in _parse_common
    cfg = _flat_namespace_to_dict(_dict_to_flat_namespace(cfg))
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.8/lib/python3.8/site-packages/jsonargparse/util.py", line 156, in _flat_namespace_to_dict
    raise_conflicting_base(k)
  File "/home/aalvarez/.virtualenvs/tts-train-XZ1ykfT_-py3.8/lib/python3.8/site-packages/jsonargparse/util.py", line 127, in raise_conflicting_base
    raise ParserError('Conflicting namespace base: '+base)
jsonargparse.util.ParserError: Conflicting namespace base: fit.data.collate_fn
```

If I change the typing to `Iterable` instead of dict and then modify the config accordingly it works just fine.
```yaml
data:
  batch_size:
    train: 30
    dev: 10
    test: 1
  collate_fn:
    - class_path: dataset.collate.AudioMelCollate
      init_args:
        max_num_frames: 32
    - class_path: dataset.collate.AudioMelCollate
      init_args:
        max_num_frames: 100
    - class_path: dataset.collate.AudioMelCollate
      init_args:
        max_num_frames: null
...
```

**Comment by mauvilsa** [comment]
The cause of many issues that gave `Conflicting namespace base` errors was related to a poor design decision for the internal representation of config objects. This was the main reason why recently there was a major restructuring which has already been finished. Please upgrade to `jsonargparse>=4.0.0` to see if works correctly.

**Comment by alealv** [comment]
Works perfectly with version **4.0.3**
Thanks!
