### ISSUE TITLE
provide an option to ignore not exists attribute when apply_*_links

### ISSUE THREAD

**Issue by tshu-w** [omni-us/jsonargparse#129]
I'm using one pytorchlightning cli for multiple data and models, which are not always have the same attribute. I suggest to provide an option to ignore not exists attribute when `apply_*_links`.

In other words, I hope to be able to have an option to no raise error in ` apply_instantiation_links` if `source_object` doesn't have the `attr`
```
def apply_instantiation_links(parser, cfg, source):
    if not hasattr(parser, "_links_group"):
        return
    for action in parser._links_group._group_actions:
        if action.apply_on != "instantiate" or source != action.source[0][1].dest:
            continue
        source_object = cfg[source]
        if action.source[0][0] == action.source[0][1].dest:
            value = action.compute_fn(source_object)
        else:
            attr = split_key_leaf(action.source[0][0])[1]
            if hasattr(source_object, attr):
                value = getattr(source_object, attr)
                if action.compute_fn is not None:
                    value = action.compute_fn(value)
                _ActionLink.set_target_value(action, value, cfg)
            else: 
                ... # logger warning
```

**Comment by mauvilsa** [comment]
This has been implemented in commit https://github.com/omni-us/jsonargparse/commit/60420ce691b41bc8e0ba1bf65c2e4a85d556942f. There is no option to disable this behavior. Always for subclasses if the source or target does not have the parameter, the linking is skipped without error. If logging is enabled at debug level, a message is shown when this happens.

**Comment by tshu-w** [comment]
@mauvilsa Hi, I'm facing new error when update to 4.5.0. Have not looked at why, it would be much appreciated if you could help look at it.

Here is my sample `cli.py`:
```python
from pytorch_lightning.utilities.cli import LightningCLI

class LitCLI(LightningCLI):
    def add_arguments_to_parser(self, parser):
        parser.link_arguments(
            "data.init_args.batch_size",
            "model.init_args.batch_size",
            apply_on="instantiate",
        )

cli = LitCLI()
```
If I run `python cli.py --help`:
```
Traceback (most recent call last):
  File "/home1/wangtianshu/lightning-template/test.py", line 7, in <module>
    cli = LitCLI()
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 551, in __init__
    self.setup_parser(run, main_kwargs, subparser_kwargs)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 587, in setup_parser
    self._add_subcommands(self.parser, **subparser_kwargs)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 661, in _add_subcommands
    subcommand_parser = self._prepare_subcommand_parser(trainer_class, subcommand, **kwargs.get(subcommand, {}))
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 669, in _prepare_subcommand_parser
    self._add_arguments(parser)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 626, in _add_arguments
    self.add_arguments_to_parser(parser)
  File "/home1/wangtianshu/lightning-template/test.py", line 5, in add_arguments_to_parser
    parser.link_arguments("data.init_args.batch_size", "model.init_args.batch_size", apply_on="instantiate")
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/jsonargparse/core.py", line 617, in link_arguments
    _ActionLink(self, source, target, compute_fn, apply_on)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/jsonargparse/actions.py", line 423, in __init__
    raise ValueError('Links applied on instantiation require source to be a subclass action or a class group.')
ValueError: Links applied on instantiation require source to be a subclass action or a class group.
```
and 
```
Traceback (most recent call last):
  File "/home1/wangtianshu/lightning-template/test.py", line 7, in <module>
    cli = LitCLI()
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 551, in __init__
    self.setup_parser(run, main_kwargs, subparser_kwargs)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 587, in setup_parser
    self._add_subcommands(self.parser, **subparser_kwargs)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 661, in _add_subcommands
    subcommand_parser = self._prepare_subcommand_parser(trainer_class, subcommand, **kwargs.get(subcommand, {}))
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 669, in _prepare_subcommand_parser
    self._add_arguments(parser)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/pytorch_lightning/utilities/cli.py", line 626, in _add_arguments
    self.add_arguments_to_parser(parser)
  File "/home1/wangtianshu/lightning-template/test.py", line 5, in add_arguments_to_parser
    parser.link_arguments("data.init_args.batch_size", "model.init_args.batch_size")
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/jsonargparse/core.py", line 617, in link_arguments
    _ActionLink(self, source, target, compute_fn, apply_on)
  File "/home1/wangtianshu/.local/share/conda/envs/template/lib/python3.9/site-packages/jsonargparse/actions.py", line 435, in __init__
    raise ValueError(f'No action for key "{key}".')
ValueError: No action for key "data.init_args.batch_size".
```

when apply_on="instantiate" and "parse" respectively.

**Comment by mauvilsa** [comment]
If you debug that script, break inside you `add_arguments_to_parser` and do `parser.print_help()` you will see that the parser does not have `data`. Without `data` there, you can't link it. If you look at

https://github.com/PyTorchLightning/pytorch-lightning/blob/6109b0b49cc1c94164bf2f40a46511096e5f655c/pytorch_lightning/utilities/cli.py#L613-L620

`data` will only be defined if you specify a data module class, e.g. `LitCLI(datamodule_class=MyDataModule)` or you register data modules.

I was not the one who extended `LightningCLI` to have registries or have the option to instantiate without specifying the module classes. If this is not clear in the documentation please create an issue in the pytorch-lightning repo or better yet, create a pull request improving the documentation where needed.

**Comment by tshu-w** [comment]
Thank you very much for investigating! I will check the documentation and determine if feedback is needed.
