### ISSUE TITLE
Error when string argument looks like a date

### ISSUE THREAD

**Issue by jaantoots** [omni-us/jsonargparse#135]
```python
from jsonargparse import ArgumentParser
parser = ArgumentParser()
parser.add_argument("foo", type=str)
parser.parse_args(["bar"])  # works as expected
parser.parse_args(["2022-04-12"])  # error: Configuration check failed :: Parser key "foo": Expected a <class 'str'> but got "2022-04-12"
```

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/typehints.py", line 328, in _check_type
    raise ex
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/typehints.py", line 316, in _check_type
    val = adapt_typehints(val, self._typehint, prev_val=prev_val, sub_add_kwargs=sub_add_kwargs)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/typehints.py", line 428, in adapt_typehints
    raise ValueError(f'Expected a {typehint} but got "{val}"')
ValueError: Expected a <class 'str'> but got "2022-04-12"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/core.py", line 1042, in check_config
    check_values(cfg)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/core.py", line 1034, in check_values
    raise ex
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/core.py", line 1031, in check_values
    self._check_value_key(action, val, key, ccfg)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/core.py", line 1255, in _check_value_key
    value = action._check_type(value, cfg=cfg)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/typehints.py", line 336, in _check_type
    raise TypeError(f'Parser key "{self.dest}"{elem}: {ex}') from ex
TypeError: Parser key "foo": Expected a <class 'str'> but got "2022-04-12"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/core.py", line 356, in parse_args
    log_message='Parsed command line arguments.',
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/core.py", line 307, in _parse_common
    self.check_config(cfg, skip_required=skip_required)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/core.py", line 1048, in check_config
    raise type(ex)(message) from ex
TypeError: Configuration check failed :: Parser key "foo": Expected a <class 'str'> but got "2022-04-12"
```

Or if the date is not a real date `parser.parse_args(["2022-04-32"])`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/typehints.py", line 308, in _check_type
    val, config_path = _parse_value_or_config(val, enable_path=self._enable_path)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/util.py", line 130, in _parse_value_or_config
    parsed_val = load_value(value)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/loaders_dumpers.py", line 97, in load_value
    return loader(value, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/loaders_dumpers.py", line 52, in yaml_load
    value = yaml.load(stream, Loader=DefaultLoader)
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 330, in construct_yaml_timestamp
    return datetime.date(year, month, day)
ValueError: day is out of range for month

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/core.py", line 346, in parse_args
    cfg, unk = self.parse_known_args(args=args, namespace=namespace)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/core.py", line 233, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/lib/python3.7/argparse.py", line 1996, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/local/lib/python3.7/argparse.py", line 1952, in consume_positionals
    take_action(action, args)
  File "/usr/local/lib/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/typehints.py", line 296, in __call__
    val = self._check_type(val, cfg=cfg)
  File "/usr/local/lib/python3.7/site-packages/jsonargparse/typehints.py", line 336, in _check_type
    raise TypeError(f'Parser key "{self.dest}"{elem}: {ex}') from ex
TypeError: Parser key "foo": day is out of range for month
```

I would expect a string argument to never be touched in any way.

Similar behaviour even when such an argument is quoted in a YAML config file, even though PyYAML behaves as expected:
```python
import yaml
yaml.load('2022-04-12')
# datetime.date(2022, 4, 12)

yaml.load('"2022-04-12"')
# '2022-04-12'
```

**Comment by mauvilsa** [comment]
Thank you very much for reporting. The default loader that `jsonargparse` uses is PyYAML which is why this is happening. Will fix it.

**Comment by mauvilsa** [comment]
Fixed in commit https://github.com/omni-us/jsonargparse/commit/15a3bb80c6888b29aafd03d5479c15257704e10f.
