### ISSUE TITLE
Error message regression in 4.15.0

### ISSUE THREAD

**Issue by Erotemic** [omni-us/jsonargparse#172]
## 🐛 Bug report

When using link_arguments incorrectly in 4.15.0 there is a difficult to parse error message, whereas in 4.14.1 the error message was much clearer.

### To reproduce

```python
import jsonargparse


class ClassA:
    def __init__(self, a=None):
        self.a = a


class ClassB(ClassA):
    def __init__(self, a=None, b=3, b_name=3, **kwargs):
        self.b = b
        self.__dict__.update(kwargs)


class ClassC:
    def __init__(self, c=None, c_name=None, **kwargs):
        self.c = c
        self.__dict__.update(kwargs)


def main():
    parser = jsonargparse.ArgumentParser()
    parser.add_subclass_arguments(ClassA, nested_key='class_a', fail_untyped=False)
    parser.add_class_arguments(ClassC, nested_key='class_c', fail_untyped=False, sub_configs=True)

    parser.link_arguments(
        "class_a.b_name",
        "class_c.c_name",
    )
    config = parser.parse_args()
    instances = parser.instantiate_classes(config)
    if hasattr(instances, 'class_a'):
        print(f'{instances.class_a.__dict__=}')
    print(f'{instances.class_c.__dict__=}')


if __name__ == '__main__':
    """
    Ignore:
        pip install jsonargparse==4.14.1
        pip install jsonargparse -U

    CommandLine:
        python jsonargparse_context_mwe.py --class_a.b_name=foo
        python jsonargparse_context_mwe.py --class_a.b_name=foo --class_a=ClassB
    """
    main()
```

If you call the CLI incorrectly (because you did not specify what type class_a is) via:

```
        python jsonargparse_context_mwe.py --class_a.b_name=foo
```

In 4.14.1 the error message is reasonably clear: 

```
usage: jsonargparse_context_mwe.py [-h] [--class_a.help CLASS_PATH_OR_NAME] [--class_a CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE] [--class_c CONFIG] [--class_c.c C]
jsonargparse_context_mwe.py: error: Configuration check failed :: Parser key "class_a": Type <class '__main__.ClassA'> expects: a class path (str); or a dict with a class_path entry; or a dict with init_args (if class path given previously). Got "NestedArg(key='b_name', val='foo')".
```

But in 4.15.0 and 4.15.1 it instead produces a much more cryptic error message:

```
Traceback (most recent call last):
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/typehints.py", line 368, in _check_type
    val, config_path = parse_value_or_config(val, enable_path=enable_path)
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/util.py", line 143, in parse_value_or_config
    parsed_val = load_value(value)
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/loaders_dumpers.py", line 111, in load_value
    loader = loaders[load_value_mode.get()]
LookupError: <ContextVar name='load_value_mode' at 0x7fdc4dc93560>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joncrall/code/watch/dev/mwe/jsonargparse_context_mwe.py", line 47, in <module>
    main()
  File "/home/joncrall/code/watch/dev/mwe/jsonargparse_context_mwe.py", line 30, in main
    config = parser.parse_args()
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/deprecated.py", line 112, in patched_parse
    cfg = parse_method(*args, _skip_check=_skip_check, **kwargs)
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/core.py", line 369, in parse_args
    parsed_cfg = self._parse_common(
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/core.py", line 297, in _parse_common
    ActionLink.apply_parsing_links(self, cfg)
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/link_arguments.py", line 227, in apply_parsing_links
    parser._check_value_key(source_action[0], cfg[source_action[0].dest], source_action[0].dest, None)
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/core.py", line 1280, in _check_value_key
    value = action._check_type(value, cfg=cfg)  # type: ignore
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/typehints.py", line 369, in _check_type
    except get_loader_exceptions():
  File "/home/joncrall/.pyenv/versions/3.10.5/envs/pyenv3.10.5/lib/python3.10/site-packages/jsonargparse/loaders_dumpers.py", line 107, in get_loader_exceptions
    return loader_exceptions[load_value_mode.get()]
LookupError: <ContextVar name='load_value_mode' at 0x7fdc4dc93560>
```

I'm not sure exactly what changed, but I'm actually getting a similar error message (although in a different context) and I have no idea how to debug it. I was able to reproduce it in this case, but in this instance I know what the "fix" is whereas in my production system I have no idea what is causing this LookupError. I'm hoping that it is some bug in how errors are reported and investigating why it is happening here will help me in my other example (which I haven't been able to get a MWE for yet).

**Comment by mauvilsa** [comment]
Thank you for reporting. I think the regression was due to commit https://github.com/omni-us/jsonargparse/commit/6e7ae6dca41d2bdf081731c042bba9d08b6f228f. I just pushed a fix in https://github.com/omni-us/jsonargparse/commit/17a0dc14344803026d04b5d401aa3605aaf63b99. Please try the current version in master with your other context to see if it is the same problem.

**Comment by Erotemic** [comment]
That commit seemed to have completely solve the issue. Thank you!
