### ISSUE TITLE
Sequence type hint not well supported

### ISSUE THREAD

**Issue by kotchin** [omni-us/jsonargparse#185]
## 🐛 Bug report

When using `Sequence` as a type hint, providing a tuple (e.g. `(2,3,4)` yields an error with the following message:
app: error: Configuration check failed :: Parser key "opt1": Expected a List but got "0"

### To reproduce

```
from jsonargparse import ArgumentParser
from typing import Sequence

parser = ArgumentParser(
    prog='app',
    description='Description for my app.'
)

parser.add_argument(
    '--opt1',
    type=Sequence,
    default=0,
    help='Help for option 1.'
)

cfg = parser.parse_args(['--opt1', '(2,3,4)'])
```
and to the following output
```
usage: app [-h] [--opt1 OPT1]
app: error: Parser key "opt1": Expected a List but got "0"
```

### Expected behavior

The expected behavior is that a tuple is a Sequence and that there is no issue with this. This can be verified: `isinstance((2,3,4), Sequence)` which evaluates to `True`.

### Environment
python=3.10
jsonargparse=4.15.2

EDIT: additionally, with a previous version of jsonargparse=4.13.2 the error message while the same, at least reports the actual value of the parameter `"(2,3,4)"` rather than `"0"`

**Comment by mauvilsa** [comment]
There is no bug. The error message is because of  `default=0` which is not a `Sequence`. If the default is commented out, it correctly shows an error message with `(2,3,4)`. The default parser mode only accepts yaml/json format, so that value is not valid. As explained in [#type-hints](https://jsonargparse.readthedocs.io/en/stable/#type-hints), "In command line arguments, config files and environment variables, tuples and sets are represented as an array". This means, the correct value to give is as:

```python
cfg = parser.parse_args(['--opt1', '[2,3,4]'])
```

**Comment by kotchin** [comment]
Thank you for your very prompt response.

I see my minimal example is not showing the scenario I'm trying to showcase.
My broader scope problem is still exhibiting the same behavior, though as above, the output is different for different jsonargparse versions.

I have a class `CWF_DataModule` whose init function contains `(ds_mean: Sequence[float] = (127.5,))`. When running my experiment, the parameters in the function are parsed using jsonargparse (for whatever reason? I'm using several other libraries, so I can't say for sure where the issue lies).

When using jsonargparse=4.13.2, my error is the following: 
```
Traceback (most recent call last):
  File "mainCLI.py", line 5, in <module>
    cli = LightningCLI(pl_FaceNet, CWF_DataModule)
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 340, in __init__
    self.parse_arguments(self.parser)
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 476, in parse_arguments
    self.config = parser.parse_args()
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/jsonargparse/deprecated.py", line 112, in patched_parse
    cfg = parse_method(*args, _skip_check=_skip_check, **kwargs)
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/jsonargparse/core.py", line 356, in parse_args
    parsed_cfg = self._parse_common(
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/jsonargparse/core.py", line 307, in _parse_common
    _ActionPrintConfig.print_config_if_requested(self, cfg)
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/jsonargparse/actions.py", line 256, in print_config_if_requested
    sys.stdout.write(subparser.dump(cfg, **parser.print_config))
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/jsonargparse/deprecated.py", line 137, in patched_dump
    return self._unpatched_dump(cfg, *args, **kwargs)
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/jsonargparse/core.py", line 679, in dump
    self._dump_cleanup_actions(cfg, self._actions, dump_kwargs)
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/jsonargparse/core.py", line 708, in _dump_cleanup_actions
    value = action.serialize(value, dump_kwargs=dump_kwargs)
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/jsonargparse/typehints.py", line 310, in serialize
    return adapt_typehints(value, self._typehint, serialize=True, sub_add_kwargs=sub_add_kwargs)
  File "miniconda3/envs/TEST_pl/lib/python3.10/site-packages/jsonargparse/typehints.py", line 564, in adapt_typehints
    raise ValueError(f'Expected a List but got "{val}"')
ValueError: Expected a List but got "(127.5,)"
```
When running jsonargparse=4.15.2, the error is much less verbose:
```
usage: mainCLI.py [-h] [-c CONFIG] [--print_config [={comments,skip_null,skip_default}+]] {fit,validate,test,predict,tune} ...
mainCLI.py: error: Parser key "data.ds_mean": Expected a List but got "(127.5,)"
```

**Comment by kotchin** [comment]
I understand. Thank you!
