### ISSUE TITLE
Path_fr does not use the default value during validation

### ISSUE THREAD

**Issue by indigoviolet** [omni-us/jsonargparse#237]
## 🐛 Bug report

If I specify a default value for a `Path_fr` parameter, the validation ignores it. This is pretty weird because clearly the value is present and used if I don't turn on this path_type validation.

### To reproduce

```python
from jsonargparse import CLI
from pathlib import Path

from jsonargparse.typing import Path_fr


def main(path: Path_fr = Path("test.py")):
    print(path)


if __name__ == "__main__":
    CLI(main, as_positional=False)
```

```
❯ python test.py --path test.py                               
test.py

❯ python test.py --help        
usage: test.py [-h] [--config CONFIG] [--print_config[=flags]] [--path PATH]

<function main at 0x7fc4001080d0>

optional arguments:
  -h, --help            Show this help message and exit.
  --config CONFIG       Path to a configuration file.
  --print_config[=flags]
                        Print the configuration after applying all other arguments and exit. The
                        optional flags customizes the output and are one or more keywords separated by
                        comma. The supported flags are: comments, skip_default, skip_null.
  --path PATH           (type: Path_fr, default: test.py)

❯ python test.py               
usage: test.py [-h] [--config CONFIG] [--print_config[=flags]] [--path PATH]
test.py: error: Configuration check failed :: Parser key "path":
  Not of type Path_fr: Expected path to be a string or a Path object.
```

### Expected behavior

The validation should happen after applying the defaults.

### Environment

- jsonargparse version: 4.19.0
- Python version (e.g., 3.9): 3.9.15
- How jsonargparse was installed (e.g. `pip install jsonargparse[all]`): `pip install jsonargparse`
- OS (e.g., Linux): Linux

**Comment by indigoviolet** [comment]
Also, bonus report: pyright reports that `Path_fr` etc are unknown import symbols in `jsonargparse.typing`

**Comment by indigoviolet** [comment]
Thanks for the explanation.

My counterargument would be that `Path_fr` and other `path_type` _should_ consider `Path`s as reasonable values (I'm agnostic to whether that is achieved by being a subclass of `pathlib.Path` or not);
otherwise it is a source of confusion and sharp edges.

Compare for example, the [os.PathLike](https://docs.python.org/3/glossary.html#term-path-like-object) protocol that is used by `os` and other stdlib functions to accept str, bytes as well as Path.

As to the other point, I feel that whatever applies to user-supplied values should also work for defaults; including checking that the default file exists and is readable.

The other confusing thing about the above messages is that jsonargparse claims that "test.py" is the default value for `--path`, but fails upon running it.

Of course, I can continue to ignore this feature if you feel strongly otherwise, but I do think it will integrate better and be more intuitive if it is compatible with Path/default values.

**Comment by mauvilsa** [comment]
There are several reasons why it shouldn't be like this, maybe just not explained well enough:

- In python when a class is used as type hint, the default value **must** be an instance of that class or a subclass. jsonargparse tries to guide people to write good code, so it will not implement behaviors that contradict correct typing.

- It is impossible to make `pathlib.Path` a subclass of the jsonargparse path types. Thus, `path: Path_fr = Path("test.py")` will never be accepted by mypy/pyright, even if unknown import symbol is fixed.

- The purpose of `Path_fr` is to guarantee that it points to a file that exists and is readable. If the default is `pathlib.Path` then there is no such guarantee. It is misleading to do this.

Note that the class/subclass requirement applies to `os.PathLike` and `str`. It is okay to have `path: os.PathLike = pathlib.Path(".")` and **not** okay `path: os.PathLike = "."`. Furthermore, in typeshed you can see that for stdlib functions, the type hints are like `str | PathLike`. Search for [StrPath](https://github.com/python/typeshed/blob/8e0b56f12ce2de74d988a6f660e215ed7f1c7a5f/stdlib/_typeshed/__init__.pyi#L134) in the [typeshed github](https://github.com/python/typeshed). Which is similar to why I suggested to use as type `Union[Path_fr, pathlib.Path]` to make the typing correct.

Also note that the jsonargparse types implement the `os.PathLike` protocol. Thus, `path: os.PathLike = Path_drw(".")` would be correct analogous to `path: os.PathLike = pathlib.Path(".")`.

> As to the other point, I feel that whatever applies to user-supplied values should also work for defaults; including checking that the default file exists and is readable.
>
> The other confusing thing about the above messages is that jsonargparse claims that "test.py" is the default value for --path, but fails upon running it.

What could be done is to also validate the defaults. If this is done, then the `--help` would fail because of the invalid default.

**Comment by indigoviolet** [comment]
I agree with your point about not breaking typing, and it makes sense from that perspective that `Path_fr` cannot receive `Path` values. 

I would like the defaults to be validated, that would both point me towards setting default values of type Path_fr and be consistent with the command line arguments.

What had confused me about the Path_fr parameter accepting Path arguments was that Path_fr accepts str from the command line, so I was expecting a similar behavior from the defaults -- but I agree that the typing principle supercedes that.

Thank you for the detailed explanation.

**Comment by mauvilsa** [comment]
> I would like the defaults to be validated, that would both point me towards setting default values of type Path_fr and be consistent with the command line arguments.

One issue with validating defaults is that parsers could be created from signatures of third party code. If the third party code has an invalid default, then there shouldn't be a blocking failure since it might not be possible to change that code. Maybe when a default does not agree with the type, there would be a warning. Also this warning would be intended for CLI developers, not for the CLI end users. So not yet sure how to do this.

**Comment by mauvilsa** [comment]
I created pull request #711. With this, people can enable validation of defaults, which means all defaults are required to be valid. Note that if this is enabled, for subclass arguments, if a class_path is given for which in the code the default is invalid, then the program will fail.

**Comment by carmocca** [comment]
I tried this feature, but it raises

```python
tests_venv/lib/python3.10/site-packages/jsonargparse/_signatures.py:103: in add_class_arguments
    added_args = self._add_signature_arguments(
tests_venv/lib/python3.10/site-packages/jsonargparse/_signatures.py:296: in _add_signature_arguments
    container = self._create_group_if_requested(
tests_venv/lib/python3.10/site-packages/jsonargparse/_signatures.py:543: in _create_group_if_requested
    group.add_argument("--" + nested_key, action=_ActionConfigLoad(basetype=config_load_type))
tests_venv/lib/python3.10/site-packages/jsonargparse/_core.py:155: in add_argument
    validate_default(self, action)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

container = <jsonargparse._core.ArgumentGroup object at 0x7f8990a73640>
action = _ActionConfigLoad(option_strings=['--job_config'], dest='job_config', nargs=None, const=None, default=None, type=None, choices=None, required=False, help='Path to a configuration file.', metavar='CONFIG')

    def validate_default(container: ActionsContainer, action: argparse.Action):
        if not isinstance(action, Action) or not get_parsing_setting("validate_defaults") or action.default is None:
            return
        try:
            with parser_context(parent_parser=container):
                default = action.default
                action.default = None
                action.default = action._check_type_(default)
        except Exception as ex:
>           raise ValueError(f"Default value is not valid: {ex}") from ex
E           ValueError: Default value is not valid: '_ActionConfigLoad' object has no attribute '_check_type'
```

Unfortunately I don't have a repro. Sharing in case the traceback is helpful

**Comment by mauvilsa** [comment]
@carmocca thank you for reporting! This should be fixed with #718. Please test it out.

**Comment by carmocca** [comment]
Sorry for my late reply. Just came back from a trip. It 4.40.0 now fails with

```python
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_typehints.py", line 556, in _check_type
    val, config_path = parse_value_or_config(val, enable_path=enable_path)
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_util.py", line 145, in parse_value_or_config
    parsed_val = load_value(value, simple_types=simple_types)
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_loaders_dumpers.py", line 190, in load_value
    mode = get_load_value_mode()
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_loaders_dumpers.py", line 144, in get_load_value_mode
    mode = parser.parser_mode
AttributeError: 'ArgumentGroup' object has no attribute 'parser_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_common.py", line 166, in validate_default
    action.default = action._check_type_(default)  # type: ignore[attr-defined]
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_common.py", line 389, in _check_type_
    return self._check_type(value, **kwargs)
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_typehints.py", line 557, in _check_type
    except get_loader_exceptions():
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_loaders_dumpers.py", line 150, in get_loader_exceptions
    mode = get_load_value_mode()
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_loaders_dumpers.py", line 144, in get_load_value_mode
    mode = parser.parser_mode
AttributeError: 'ArgumentGroup' object has no attribute 'parser_mode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/work/bin/script", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/carlos/my_code/__main__.py", line 51, in main
    parser.add_function_arguments(launch, skip={"filepath", "config"})
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_signatures.py", line 224, in add_function_arguments
    return self._add_signature_arguments(
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_signatures.py", line 308, in _add_signature_arguments
    self._add_signature_parameter(
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_signatures.py", line 432, in _add_signature_parameter
    action = container.add_argument(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_core.py", line 156, in add_argument
    validate_default(self, action)
  File "/home/ubuntu/.pyenv/versions/work/lib/python3.10/site-packages/jsonargparse/_common.py", line 168, in validate_default
    raise ValueError(f"Default value is not valid: {ex}") from ex
ValueError: Default value is not valid: 'ArgumentGroup' object has no attribute 'parser_mode'
```

**Comment by mauvilsa** [comment]
@carmocca could you please provide a reproduction script for the error above. The unit tests related to this feature work fine and I am not sure how to make this failure happen.

**Comment by carmocca** [comment]
Finally got a chance to repro. Sorry for the long wait

```python
from dataclasses import dataclass

@dataclass
class Foo:
    foo: str = "foo"

@dataclass
class Bar:
    foo: Foo

from jsonargparse import ArgumentParser, ActionConfigFile, set_parsing_settings

set_parsing_settings(validate_defaults=True)
parser = ArgumentParser()
parser.add_argument("-c", "--config", action=ActionConfigFile)
parser.add_function_arguments(Bar)
args = parser.parse_args()
print(args)
```

```shell
$ python repro.py
Traceback (most recent call last):
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_typehints.py", line 558, in _check_type
    val, config_path = parse_value_or_config(val, enable_path=enable_path)
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_util.py", line 145, in parse_value_or_config
    parsed_val = load_value(value, simple_types=simple_types)
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_loaders_dumpers.py", line 198, in load_value
    mode = get_load_value_mode()
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_loaders_dumpers.py", line 152, in get_load_value_mode
    mode = parser.parser_mode
AttributeError: 'ArgumentGroup' object has no attribute 'parser_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_common.py", line 168, in validate_default
    action.default = action._check_type_(default)  # type: ignore[attr-defined]
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_common.py", line 391, in _check_type_
    return self._check_type(value, **kwargs)
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_typehints.py", line 559, in _check_type
    except get_loader_exceptions():
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_loaders_dumpers.py", line 158, in get_loader_exceptions
    mode = get_load_value_mode()
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_loaders_dumpers.py", line 152, in get_load_value_mode
    mode = parser.parser_mode
AttributeError: 'ArgumentGroup' object has no attribute 'parser_mode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/carlos/titan/repro.py", line 16, in <module>
    parser.add_function_arguments(Bar)
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_signatures.py", line 224, in add_function_arguments
    return self._add_signature_arguments(
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_signatures.py", line 308, in _add_signature_arguments
    self._add_signature_parameter(
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_signatures.py", line 447, in _add_signature_parameter
    action = container.add_argument(*args, **kwargs)
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_core.py", line 137, in add_argument
    self.add_class_arguments(kwargs.pop("type"), nested_key, **kwargs)
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_signatures.py", line 103, in add_class_arguments
    added_args = self._add_signature_arguments(
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_signatures.py", line 308, in _add_signature_arguments
    self._add_signature_parameter(
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_signatures.py", line 447, in _add_signature_parameter
    action = container.add_argument(*args, **kwargs)
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_core.py", line 157, in add_argument
    validate_default(self, action)
  File "/home/ubuntu/carlos/titan/.venv/lib/python3.10/site-packages/jsonargparse/_common.py", line 170, in validate_default
    raise ValueError(f"Default value is not valid: {ex}") from ex
ValueError: Default value is not valid: 'ArgumentGroup' object has no attribute 'parser_mode'
```

**Comment by mauvilsa** [comment]
@carmocca thanks for the repro. This will be fixed with #771.

One question. In the repro, was the use of `add_function_arguments` intended or a mistake? I ask because a dataclass is not a function. So unexpected that it was used and also unexpected that it works.

**Comment by carmocca** [comment]
It's a mistake when I minimized the repro. In my real script Im using a function that then takes a dataclass
