### ISSUE TITLE
Cannot pass saving check when linking to required value of dataclass parameter of subclass argument

### ISSUE THREAD

**Issue by function2-llx** [omni-us/jsonargparse#332]
### To reproduce

```python
from dataclasses import dataclass

from jsonargparse import ArgumentParser

class A:
    def __init__(self, a: int):
        pass

@dataclass
class B:
    a: int

class C:
    def __init__(self, b: B):
        pass

def main():
    parser = ArgumentParser()
    parser.add_class_arguments(A, 'a')
    parser.add_subclass_arguments(C, 'c')
    parser.link_arguments('a.a', 'c.init_args.b.a')
    args = parser.parse_args(['--a.a', '1', '--c', '__main__.C'])
    parser.save(args, 'test.yaml', overwrite=True)

if __name__ == '__main__':
    main()
```

### Expected behavior

The config is saved normally.

### Actual Result

```
Traceback (most recent call last):
  File ".../jsonargparse/_core.py", line 1025, in check_required
    val = cfg[reqkey]
          ~~~^^^^^^^^
  File ".../jsonargparse/_namespace.py", line 211, in __getitem__
    leaf_key, parent_ns, _ = self._parse_required_key(key)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_namespace.py", line 172, in _parse_required_key
    raise KeyError(f'Key "{key}" not found in namespace.')
KeyError: 'Key "b.a" not found in namespace.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../jsonargparse/_core.py", line 1068, in check_config
    check_required(cfg, self)
  File ".../jsonargparse/_core.py", line 1029, in check_required
    raise TypeError(
TypeError: Key "b.a" is required but not included in config object or its value is None.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../jsonargparse/_core.py", line 436, in parse_object
    parsed_cfg = self._parse_common(
                 ^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_core.py", line 314, in _parse_common
    self.check_config(cfg, skip_required=skip_required)
  File ".../jsonargparse/_core.py", line 1076, in check_config
    raise type(ex)(message) from ex
TypeError: Configuration check failed :: Key "b.a" is required but not included in config object or its value is None.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../jsonargparse/_typehints.py", line 828, in adapt_typehints
    val = adapt_class_type(val, serialize, instantiate_classes, sub_add_kwargs, prev_val=prev_val)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_typehints.py", line 1066, in adapt_class_type
    init_args = parser.parse_object(init_args, cfg_base=prev_init_args, defaults=sub_defaults.get())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_deprecated.py", line 122, in patched_parse
    cfg = parse_method(*args, _skip_check=_skip_check, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_core.py", line 446, in parse_object
    self.error(str(ex), ex)
  File ".../jsonargparse/_core.py", line 988, in error
    raise argument_error(message) from ex
argparse.ArgumentError: Configuration check failed :: Key "b.a" is required but not included in config object or its value is None.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../jsonargparse/_typehints.py", line 474, in _check_type
    raise ex
  File ".../jsonargparse/_typehints.py", line 462, in _check_type
    val = adapt_typehints(val, self._typehint, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_typehints.py", line 832, in adapt_typehints
    raise_unexpected_value(f"Problem with given class_path {class_path!r}:\n{error}", exception=ex)
  File ".../jsonargparse/_typehints.py", line 549, in raise_unexpected_value
    raise ValueError(message) from exception
ValueError: Problem with given class_path '__main__.C':
  Configuration check failed :: Key "b.a" is required but not included in config object or its value is None.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../jsonargparse/_core.py", line 1070, in check_config
    check_values(cfg)
  File ".../jsonargparse/_core.py", line 1060, in check_values
    raise ex
  File ".../jsonargparse/_core.py", line 1055, in check_values
    self._check_value_key(action, val, key, ccfg)
  File ".../jsonargparse/_core.py", line 1296, in _check_value_key
    value = action._check_type(value, cfg=cfg)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_typehints.py", line 484, in _check_type
    raise TypeError(f'Parser key "{self.dest}"{elem}:\n{error}') from ex
TypeError: Parser key "c":
  Problem with given class_path '__main__.C':
    Configuration check failed :: Key "b.a" is required but not included in config object or its value is None.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    main()
  File "test.py", line 23, in main
    parser.save(args, 'test.yaml', overwrite=True, multifile=True)
  File ".../jsonargparse/_deprecated.py", line 158, in patched_save
    return self._unpatched_save(cfg, *args, multifile=multifile, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_core.py", line 822, in save
    self.check_config(strip_meta(cfg), branch=branch)
  File ".../jsonargparse/_core.py", line 1076, in check_config
    raise type(ex)(message) from ex
TypeError: Parser key "c":
  Problem with given class_path '__main__.C':
    Configuration check failed :: Key "b.a" is required but not included in config object or its value is None.
```

### Environment

- jsonargparse version: 4.22.1
- Python version: 3.11.4
- How jsonargparse was installed: `pip install jsonargparse[signatures]`
- OS: Ubuntu 22.04

**Comment by mauvilsa** [comment]
Thank you for reporting! I created pull request #333 with a fix. Please check.

**Comment by function2-llx** [comment]
Thanks for the fix. Sorry that I'm not quite familiar with the jsonargparse code and I may not provide reliable suggestions. I've simply checked the fix (it looks good) and run the example with fixed code locally, it works fine now.

**Comment by mauvilsa** [comment]
Perfect. Thank you!
