### ISSUE TITLE
Unpacking Namespace object expands all nested Namespace objects, leading to unexpected behavior

### ISSUE THREAD

**Issue by function2-llx** [omni-us/jsonargparse#345]
## 🐛 Bug report

When unpacking a nested Namespace object, the nested Namespace objects will also be unpacked. E.g., `**Namespace(a=Namespace(b=1))` will results in `{'a.b': 1}`. This can lead to some unexpected behavior, such as instantiation failure when a Namespace object is an argument.

### To reproduce

```python
from jsonargparse import ArgumentParser, Namespace

class A:
    def __init__(self, cfg: Namespace):
        self.cfg = cfg

def main():
    parser = ArgumentParser()
    parser.add_class_arguments(A, 'a')
    args = parser.parse_args(['--a.cfg.class_path', 'jsonargparse.Namespace'])
    args = parser.instantiate_classes(args)
    print(args)

if __name__ == '__main__':
    main()
```

### Expected behavior

The class is instantiated properly

### Actual Result

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    main()
  File "test.py", line 11, in main
    args = parser.instantiate_classes(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_deprecated.py", line 139, in patched_instantiate_classes
    cfg = self._unpatched_instantiate_classes(cfg, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../jsonargparse/_core.py", line 1124, in instantiate_classes
    component.instantiate_class(component, cfg)
  File ".../jsonargparse/_signatures.py", line 561, in group_instantiate_class
    parent[key] = group.group_class(**value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: A.__init__() got an unexpected keyword argument 'cfg.class_path'
```

### Environment

- jsonargparse version: 4.23.1
- Python version: 3.11.4
- How jsonargparse was installed: `pip install jsonargparse[all]`
- OS: Ubuntu 22.04

**Comment by mauvilsa** [comment]
The `Namespace` class should not be used as a type hint. The way this class behaves is central to how things work internally in jsonargparse. Most likely it is not possible to change this. Furthermore, having a god-like parameter such as `cfg` with a type that accepts unbounded values is an anti-pattern, so it should be discouraged. I would not even spend time on looking into it.

Regarding your actual use case, in general you should define parameters and types such that they accurately represent what is being expected. When a parameter is needed to get a class instance, then use dependency injection. For the case of an optimizer (pytorch-style), this is even included in the docs as an example, see [callable-type](https://jsonargparse.readthedocs.io/en/v4.23.1/#callable-type). Also you can have a look at how this works in lightning, see [lightning_cli_advanced_3.html#multiple-optimizers-and-schedulers](https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced_3.html#multiple-optimizers-and-schedulers).

If one or a group settings are needed more than once, then the CLI user should only need to provide once, and this can be passed to other places via [argument-linking](https://jsonargparse.readthedocs.io/en/v4.23.1/#argument-linking).

**Comment by function2-llx** [comment]
Hi @mauvilsa , thank you for your suggestions! I provide the example with a `cfg` parameter with `Namespace` type to make it minimal (I actually don't use that), and I'm sorry for the confusion.
I also feel sorry that I'm not so familiar with the concept of `jsonargparse` and sometimes I may not report issues valuable enough. I greatly appreciate your patience and work.

**Comment by mauvilsa** [comment]
> I also feel sorry that I'm not so familiar with the concept of jsonargparse and sometimes I may not report issues valuable enough.

Please, ask as much as you need! It is no problem if some proposal does not fit. The documentation became a bit long and not easy to understand how/when to use each of the features.

> I provide the example with a cfg parameter with Namespace type to make it minimal (I actually don't use that), and I'm sorry for the confusion.

Now worries. I wasn't confused since you mentioned your actual use case. The reason I made emphasis on the `Namespace` type was to give more context to anyone that lands here looking for information.
