### ISSUE TITLE
Parser mode is not inherited by subparsers when adapting typehints

### ISSUE THREAD

**Issue by a-gardner1** [omni-us/jsonargparse#563]
## 🐛 Bug report

The parsing mode is not passed to subparsers created in [`ActionTypeHint.get_class_parser`](https://github.com/omni-us/jsonargparse/blob/54ff57e6f22c3502fc478238714e8b8ba646fe01/jsonargparse/_typehints.py#L611), which can manifest in bugs such as a `yaml.representer.RepresenterError` when the subparser encounters a key that requires a non-default parsing mode.

The following script provides a simple contrived example that demonstrates the bug wherein the custom parsing mode loads arbitrary constants (such as functions) identified with the key `"constant_path"` analogous to `"class_path"`.
Whereas the custom dumper would convert the function object into a `{"constant_path": path.to.function}` dictionary, the default dumper used by the subparser crashes as it doesn't know how to handle the raw function object.

I believe that this can be fixed by simply passing `parser_mode=parser.parser_mode` on [this line](https://github.com/omni-us/jsonargparse/blob/54ff57e6f22c3502fc478238714e8b8ba646fe01/jsonargparse/_typehints.py#L618) of `ActionTypeHint.get_class_parser`.
In the meantime, a workaround is simply to override the default `"yaml"` parser mode with your own with `jsonargparse.set_loader`/`set_dumper`.

### To reproduce

```python
import inspect
import tempfile
import typing
from argparse import Namespace
from dataclasses import dataclass, field
from typing import Any, TypeVar

import jsonargparse
import yaml
from jsonargparse import ActionConfigFile, ArgumentParser, lazy_instance
from jsonargparse._loaders_dumpers import yaml_dump, yaml_load
from jsonargparse._util import import_object

_T = TypeVar('_T')

_VALUE_PATH = 'constant_path'



####################### Set up custom parser mode #######################


def is_constant_spec(value: Any) -> bool:
    is_constant = isinstance(value, (dict, Namespace)) and _VALUE_PATH in value
    if is_constant:
        allowed_keys = {
            _VALUE_PATH,
        }
        keys = getattr(value, "__dict__", value).keys()
        is_constant = len(set(keys) - allowed_keys) == 0
    return is_constant


def try_import_value(config: _T | dict[str, Any] | Namespace) -> _T | Any:
    if is_constant_spec(config):
        assert isinstance(config, (dict, Namespace))
        config = typing.cast(
            dict[str,
                 Any],
            getattr(config,
                    "__dict__",
                    config))
        return import_object(config[_VALUE_PATH])
    else:
        return config


def _yaml_constant_load(config: Any) -> Any:
    if is_constant_spec(config):
        return try_import_value(config)
    elif isinstance(config, (dict, Namespace)):
        config = typing.cast(
            dict[str,
                 Any],
            getattr(config,
                    "__dict__",
                    config))
        return {
            k: _yaml_constant_load(v) for k,
            v in config.items()
        }
    elif isinstance(config, (list, set, tuple)):
        return type(config)(_yaml_constant_load(v) for v in config)
    else:
        return config


def yaml_constant_load(stream: str) -> Any:
    value = yaml_load(stream)  # type: ignore[no-untyped-call]
    return _yaml_constant_load(value)


def _yaml_constant_dump(config: Any) -> Any:
    if inspect.isfunction(config):
        return {
            "constant_path": f"{config.__module__}.{config.__name__}"
        }
    elif isinstance(config, (dict, Namespace)):
        config = typing.cast(
            dict[str,
                 Any],
            getattr(config,
                    "__dict__",
                    config))
        return {
            k: _yaml_constant_dump(v) for k,
            v in config.items()
        }
    elif isinstance(config, (list, set, tuple)):
        return type(config)(_yaml_constant_dump(v) for v in config)
    else:
        return config


def yaml_constant_dump(config: Any) -> str:
    config = _yaml_constant_dump(config)
    return typing.cast(str, yaml_dump(config))  # type: ignore


jsonargparse.set_loader('constant_load', yaml_constant_load)
jsonargparse.set_dumper("constant_load", yaml_constant_dump)

################################ MWE ###################################


@dataclass
class TestInner:

    inner_kwargs: dict[str, Any] | None = None


@dataclass
class Test:

    tests: list[TestInner] = field(default_factory=lambda: [])


def foo() -> int:
    return 42


parser = ArgumentParser(exit_on_error=False, parser_mode='constant_load')
parser.add_argument(
    "-c",
    "--config",
    action=ActionConfigFile,
    help="Path to a configuration file in json or yaml format.")
parser.add_class_arguments(
    Test,
    "test",
    fail_untyped=False,
    instantiate=True,
    sub_configs=True,
    default=lazy_instance(
        Test,
    ),
)
# parser.add_argument("--config", action=ActionConfigFile)

config = yaml.safe_dump(
    {
        "test":
            {
                "tests":
                    [
                        {
                            "inner_kwargs":
                                {
                                    "function":
                                        {
                                            "constant_path": f'{__name__}.foo'
                                        }
                                }
                        }
                    ]
            }
    })

with tempfile.NamedTemporaryFile("w", suffix=".yaml") as f:
    f.write(config)
    f.flush()
    cfg = parser.parse_args(["--config", f"{f.name}"])

print(parser.dump(cfg, skip_link_targets=False, skip_none=False))
```

### Expected behavior

The script should print the following:
```yaml
test:
  tests:
  - inner_kwargs:
      function:
        constant_path: __main__.foo
```

### Actual behavior

`yaml.representer.RepresenterError: ('cannot represent an object', <function foo at 0x7f5ddc21c400>)`

<details>
<summary>Traceback</summary>

```python
Traceback (most recent call last):
  File ".../lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File ".../scripts/test_jsonargparse.py", line 161, in <module>
    print(parser.dump(cfg, skip_link_targets=False, skip_none=False))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/jsonargparse/_deprecated.py", line 150, in patched_dump
    return self._unpatched_dump(cfg, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/jsonargparse/_core.py", line 730, in dump
    self._dump_cleanup_actions(cfg, self._actions, dump_kwargs)
  File ".../lib/python3.11/site-packages/jsonargparse/_core.py", line 763, in _dump_cleanup_actions
    value = action.serialize(value, dump_kwargs=dump_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/jsonargparse/_typehints.py", line 497, in serialize
    return adapt_typehints(
           ^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/jsonargparse/_typehints.py", line 878, in adapt_typehints
    val[n] = adapt_typehints(v, subtypehints[0], list_item=True, **adapt_kwargs_n)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/jsonargparse/_typehints.py", line 987, in adapt_typehints
    val = load_value(parser.dump(val, **dump_kwargs.get()))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/jsonargparse/_deprecated.py", line 150, in patched_dump
    return self._unpatched_dump(cfg, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/jsonargparse/_core.py", line 741, in dump
    return dump_using_format(self, cfg_dict, "yaml_comments" if yaml_comments else format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/jsonargparse/_loaders_dumpers.py", line 179, in dump_using_format
    dump = dumpers[dump_format](*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/jsonargparse/_loaders_dumpers.py", line 134, in yaml_dump
    return yaml.safe_dump(data, **dump_yaml_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/__init__.py", line 269, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File ".../lib/python3.11/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', <function foo at 0x7f5ddc21c400>)
```
</details>

### Environment

- jsonargparse version: 4.28.0
- Python version: 3.11.6
- How jsonargparse was installed: `pip`
- OS: Ubuntu 20.04

**Comment by mauvilsa** [comment]
Thank you for reporting! This fixed in #564. Indeed passing `parser_mode` in `ActionTypeHint.get_class_parser` was missing. It was somewhat difficult to come up with a small reproduction example to use as unit test, but what you provided was for sure very helpful.
