### ISSUE TITLE
Support for subcommands and `instantiate_classes`

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#70]
I'm trying to use subcommands and `instantiate_classes` together.

Without subcommand, everything works properly:

```python
from jsonargparse import ArgumentParser

class Foo:
    def __init__(self, a: int = 1):
        ...

parser = ArgumentParser(parse_as_dict=True)
key = "foo"
parser.add_class_arguments(Foo, key)

config = parser.parse_args()
print(config)
config_init = parser.instantiate_classes(config)
# the class should be instantiated
print(config_init)
assert isinstance(config_init[key], Foo)
```

```python
{'foo': {'a': 1}}
{'foo': <__main__.Foo object at 0x102fc90d0>}
```

However, with subcommand enabled, seems like `instantiate_classes` does not act recursively.

```python
from jsonargparse import ArgumentParser

class Foo:
    def __init__(self, a: int = 1):
        ...

parser = ArgumentParser(parse_as_dict=True)
subcommands = parser.add_subcommands()
subparser = ArgumentParser()
key = "foo"
subparser.add_class_arguments(Foo, key)
subcommand = "cmd"
subcommands.add_subcommand(subcommand, subparser)

config = parser.parse_args([subcommand])
print(config)
# the class should be instantiated even if it is under a subcommand
config_init = parser.instantiate_classes(config)
print(config_init)
assert isinstance(config_init[subcommand][key], Foo)
```

```python
{'subcommand': 'cmd', 'cmd': {'foo': {'a': 1}}}
{'subcommand': 'cmd', 'cmd': {'foo': {'a': 1}}}
Traceback (most recent call last):
  File "script.py", line 33, in <module>
    assert isinstance(config_init[subcommand][key], Foo)
AssertionError
```

I would expect the second print to be

```python
{'subcommand': 'cmd', 'cmd': {'foo': <__main__.Foo object at 0x102fc90d0>}}
```

Not sure if this is a bug or a feature. Is this not a valid way to instantiate classes under subcommands?

If I try to do instead

```python
config_init = parser.instantiate_classes(config["subcommand"])
print(config_init)
```

I get:

```python
Traceback (most recent call last):
  File "/Users/carlosmocholi/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/scratch_12.py", line 32, in <module>
    config_init = parser.instantiate_classes(config["subcommand"])
  File "/Users/carlosmocholi/.pyenv/versions/3.9.1/envs/lightning-3.9/lib/python3.9/site-packages/jsonargparse/core.py", line 1103, in instantiate_classes
    cfg = strip_meta(cfg)
  File "/Users/carlosmocholi/.pyenv/versions/3.9.1/envs/lightning-3.9/lib/python3.9/site-packages/jsonargparse/util.py", line 247, in strip_meta
    cfg = namespace_to_dict(cfg)
  File "/Users/carlosmocholi/.pyenv/versions/3.9.1/envs/lightning-3.9/lib/python3.9/site-packages/jsonargparse/util.py", line 233, in namespace_to_dict
    return expand_namespace(cfg_ns)
  File "/Users/carlosmocholi/.pyenv/versions/3.9.1/envs/lightning-3.9/lib/python3.9/site-packages/jsonargparse/util.py", line 224, in expand_namespace
    cfg = dict(vars(cfg))
TypeError: vars() argument must have __dict__ attribute
```

**Comment by mauvilsa** [comment]
I guess I never implemented the instantiation when using subcommands. Could be considered a bug or a missing feature. The correct way would be `config_init = parser.instantiate_classes(config)`. Will look into it.
