### ISSUE TITLE
`KeyError` with subcommands and config files

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#80]
```python
from jsonargparse import ArgumentParser

class Foo:
    def __init__(self, a: int = 1):
        ...


parser = ArgumentParser(parse_as_dict=True, error_handler=None)
subcommands = parser.add_subcommands()
subparser = ArgumentParser()
key = "foo"
subparser.add_class_arguments(Foo, key)
subcommand = "cmd"
subcommands.add_subcommand(subcommand, subparser)

config = {'a': 3}
config = parser.parse_args([subcommand, "--config", config])
assert config[subcommand]['a'] == 3
```

Produces (after removing the try-except in `ArgumentParser.parse_args`):

```python
Traceback (most recent call last):
  File "/Users/carlosmocholi/git/jsonargparse/jsonargparse/core.py", line 381, in parse_args
    cfg, unk = self.parse_known_args(args=args)
  File "/Users/carlosmocholi/git/jsonargparse/jsonargparse/core.py", line 256, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/carlosmocholi/.pyenv/versions/3.9.1/lib/python3.9/argparse.py", line 1895, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/Users/carlosmocholi/git/jsonargparse/jsonargparse/core.py", line 269, in _parse_optional
    return super()._parse_optional(arg_string)
  File "/Users/carlosmocholi/.pyenv/versions/3.9.1/lib/python3.9/argparse.py", line 2182, in _parse_optional
    if not arg_string[0] in self.prefix_chars:
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/carlosmocholi/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/scratch_11.py", line 17, in <module>
    config = parser.parse_args([subcommand, "--config", config])
  File "/Users/carlosmocholi/git/jsonargparse/jsonargparse/core.py", line 397, in parse_args
    self.error(str(ex), ex)
  File "/Users/carlosmocholi/git/jsonargparse/jsonargparse/core.py", line 991, in error
    raise ParserError(message) from ex
jsonargparse.util.ParserError: 0
```

The same happens if I pass the subcommand inside the config:

```python
parser = ArgumentParser(parse_as_dict=True, error_handler=None)
subcommands = parser.add_subcommands()
subparser = ArgumentParser()
key = "foo"
subparser.add_class_arguments(Foo, key)
subcommand = "cmd"
subcommands.add_subcommand(subcommand, subparser)

config = {'subcommand': subcommand, subcommand: {'a': 3}}
config = parser.parse_args(["--config", config])
assert config[subcommand]['a'] == 3
```

Environment: current master

**Comment by mauvilsa** [comment]
@carmocca can you please modify the code snippet so that it reproduces the stack trace. Currently it doesn't. Also please do not modify the source code. Instead do `parser = ArgumentParser(parse_as_dict=True, error_handler=None)`.

**Comment by carmocca** [comment]
Did not know about `error_handler = None`. I've updated the top post.

**Comment by mauvilsa** [comment]
There are three mistakes in the first code snippet. 1) `subparser` is missing `add_argument('--config', action=ActionConfigFile)`; 2) the config should be `{'foo': {'a': 3}}` and 3) `parse_args` should only receive a list of strings and it is getting a dict. I think everything is working as expected, thus closing this.
