### ISSUE TITLE
`TypeError`: subcommands and `link_arguments`

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#82]
## Reproduction

```python
from jsonargparse import ArgumentParser

class Foo:
    def __init__(self, a: int):
        self.a = a

    def __repr__(self):
        return f"Foo(a={self.a})"

parser = ArgumentParser(parse_as_dict=True)
subparser = ArgumentParser()

subcommands = parser.add_subcommands()
subparser.add_class_arguments(Foo, nested_key="foo")
subparser.add_argument("--b", type=int)
subparser.link_arguments("b", "foo.a")
subcommands.add_subcommand("cmd", subparser)

config = parser.parse_args(["cmd", "--b=2"])
print(config)

config_init = parser.instantiate_classes(config)
print(config_init)
```

## Actual:
```python
{'subcommand': 'cmd', 'cmd': {'b': 2}}
Traceback (most recent call last):
  File "/Users/carlosmocholi/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/scratch_11.py", line 22, in <module>
    config_init = parser.instantiate_classes(config)
  File "/Users/carlosmocholi/git/jsonargparse/jsonargparse/core.py", line 1115, in instantiate_classes
    cfg[subcommand] = subparser.instantiate_classes(cfg[subcommand], instantiate_groups=instantiate_groups)
  File "/Users/carlosmocholi/git/jsonargparse/jsonargparse/core.py", line 1109, in instantiate_classes
    component.instantiate_class(component, cfg)
  File "/Users/carlosmocholi/git/jsonargparse/jsonargparse/signatures.py", line 550, in group_instantiate_class
    parent[key] = group.group_class(**value)
TypeError: __init__() missing 1 required positional argument: 'a'
```

## Expected:

```python
{'subcommand': 'cmd', 'cmd': {'foo': {'a': 2}, 'b': 2}}
{'subcommand': 'cmd', 'cmd': {'foo': Foo(a=2), 'b': 2}}
```

## Context:

Encountered in https://github.com/PyTorchLightning/pytorch-lightning/pull/7508#discussion_r690851814

**Comment by mauvilsa** [comment]
This is now fixed in master.
