### ISSUE TITLE
lazy_instance could not be applied for torch.nn.Module

### ISSUE THREAD

**Issue by quancs** [omni-us/jsonargparse#96]
code:
```
>>> import torch.nn as nn
>>> from jsonargparse import lazy_instance
>>> lazy_instance(nn.Module)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quancs/miniconda3/lib/python3.8/site-packages/jsonargparse/typehints.py", line 561, in lazy_instance
    return LazyInitClass(class_type, kwargs)
  File "/home/quancs/miniconda3/lib/python3.8/site-packages/jsonargparse/typehints.py", line 520, in __init__
    for name, method in inspect.getmembers(self, predicate=inspect.ismethod):
  File "/home/quancs/miniconda3/lib/python3.8/inspect.py", line 334, in getmembers
    names = dir(object)
  File "/home/quancs/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1557, in __dir__
    parameters = list(self._parameters.keys())
  File "/home/quancs/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LazyInitClass' object has no attribute '_parameters'
```

**Comment by mauvilsa** [comment]
Thanks for reporting. Indeed it is not working and after trying a few things I still don't understand what is the underlying issue. Implementing `__dir__` is not a solution since you would need to manually give all possible methods that could be called with an instance. Will keep looking at how to fix it.

**Comment by mauvilsa** [comment]
I have pushed a fix to master. The `lazy_instance` idea isn't as simple as I initially thought. There might be classes for which it still does not work. Specific issues can be created if this is the case. For now closing this one.
